### ISSUE TITLE
error Protocol

### ISSUE THREAD

**Issue by jakubartur** [DurianStallSingapore/Zilliqa-Mining-Proxy#37]
(venv) xx@pool ~/Zilliqa-Mining-Proxy # python3 start.py
Traceback (most recent call last):
  File "start.py", line 24, in <module>
    from zilpool import poolserver
  File "/root/Zilliqa-Mining-Proxy/zilpool/poolserver.py", line 28, in <module>
    from jsonrpcserver import async_dispatch
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/jsonrpcserver/__init__.py", line 19, in <module>
    from .async_main import (
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/jsonrpcserver/async_main.py", line 5, in <module>
    from .async_dispatcher import dispatch_to_response_pure
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 9, in <module>
    from oslash.either import Left  # type: ignore
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/oslash/__init__.py", line 2, in <module>
    from .typing import Functor, Applicative, Monoid, Monad
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/oslash/typing/__init__.py", line 2, in <module>
    from .applicative import Applicative
  File "/root/Zilliqa-Mining-Proxy/venv/lib/python3.7/site-packages/oslash/typing/applicative.py", line 3, in <module>
    from typing import Callable, TypeVar, Protocol
ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)
(venv) xx@pool ~/Zilliqa-Mining-Proxy #

me use 
python3 --version
Python 3.7.5
any idea why fix ?

**Comment by jakubartur** [comment]
with this, it works on 3.8 but there is no mining. Can I download the constants.xml file with conf under the proxy? I have the impression that there is something wrong with my conf
